begin;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  product_no text not null,
  product_name text not null,
  wholesale_price numeric(12,2),
  image_url text,
  is_active boolean not null default true,
  display_order integer not null,
  effective_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_active_price_check check (
    not is_active or (wholesale_price is not null and wholesale_price > 0)
  )
);

create index if not exists products_product_no_idx on public.products (product_no);
create index if not exists products_display_order_idx on public.products (display_order, id);

alter table public.products enable row level security;
revoke all on table public.products from anon, authenticated;
grant select on table public.products to authenticated;

drop policy if exists products_active_staff_select on public.products;
create policy products_active_staff_select
on public.products
for select
to authenticated
using (
  exists (
    select 1
    from public.exhibition_staff staff
    where staff.user_id = (select auth.uid())
      and staff.active = true
  )
);

create table if not exists public.exhibition_accounts (
  id bigint generated by default as identity primary key,
  account_name text not null unique,
  display_order integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists exhibition_accounts_display_order_idx
on public.exhibition_accounts (display_order, id);

alter table public.exhibition_accounts enable row level security;
revoke all on table public.exhibition_accounts from anon, authenticated;
grant select on table public.exhibition_accounts to authenticated;

drop policy if exists exhibition_accounts_active_staff_select on public.exhibition_accounts;
create policy exhibition_accounts_active_staff_select
on public.exhibition_accounts
for select
to authenticated
using (
  exists (
    select 1
    from public.exhibition_staff staff
    where staff.user_id = (select auth.uid())
      and staff.active = true
  )
);

commit;;
